volumes:
  postgres_client_data:
    driver: local

services:
  postgres-client:
    image: postgres:latest
    container_name: postgres-client
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: client_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_client_data:/var/lib/postgresql/data
  client-service:
    build:
      context: ./Client-Service
      dockerfile: Dockerfile
    container_name: client-service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-client:5432/client_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres-client