server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: test
          uri: https://httpbin.org
          predicates:
            - Path=/get

logging:
  level:
    org.springframework.cloud.gateway: DEBUG